### ISSUE TITLE
Allow non font awesome icons?

### ISSUE THREAD

**Issue by elgs** [fortunar/react-sidemenu#4]
I'm hoping to use some non font awesome icons. Looking into the source code, I found some line like this:

```jsx
<i className={`fa ${item.icon} item-icon`} />
```

I am wondering if it is better to remove the `fa` from the library code so that it will not be limited to fa icons. From the end user's perspective, if we want to use fa icons, we simply add `fa `.

**Comment by wamujlb** [comment]
It will be awesome. Nice idea.

**Comment by fortunar** [comment]
This can already be achieved if you override 'renderMenuItemContent' method.

**Comment by OleksandrBohuslavskyi** [comment]
@fortunar handleRenderMenuItemContent() method actually. And also renderChevron() method, because it's also uses "font awesome". And need to do it in two classes: SideMenu and Item

![screen](https://content.screencast.com/users/kenobit/folders/Jing/media/776c450e-64fd-4147-9dbd-9dea68c5444b/2017-09-13_1746.png)
